/*
 * Build-time-only tooling. Renders the lesson formulas to static HTML+MathML
 * with KaTeX, so the ~280KB KaTeX runtime never ships to the browser — only the
 * pre-rendered markup (and katex.css) does.
 *
 * Run: npm run gen:formulas
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import katex from "katex";

// Each entry: a TeX string and the plain-language reading a screen reader hears
// (set as the container aria-label, which overrides the visual markup).
const FORMULAS: Record<string, { tex: string; aria: string }> = {
  takeMax: {
    tex: String.raw`N=\max\bigl(n_1,\,n_2,\,n_3,\,n_4\bigr)`,
    aria: "The required sample size N is the maximum of the sample sizes from each criterion.",
  },
  riskPrecision: {
    tex: String.raw`n=\left(\frac{1.96}{\delta}\right)^{2}\,\varphi\,(1-\varphi)`,
    aria: "n equals 1.96 over delta, squared, times phi times one minus phi. Delta is the target margin of error, 0.05.",
  },
  mape: {
    tex: String.raw`n=\exp\!\left(\frac{-0.508+0.259\ln\varphi+0.504\ln P-\ln(0.05)}{0.544}\right)`,
    aria: "n equals the exponential of the quantity, minus 0.508 plus 0.259 times the natural log of phi plus 0.504 times the natural log of P minus the natural log of 0.05, all divided by 0.544.",
  },
  shrinkage: {
    tex: String.raw`n=\frac{P}{(S-1)\,\ln\!\left(1-\dfrac{R^{2}_{cs}}{S}\right)}`,
    aria: "n equals P divided by, S minus 1, times the natural log of one minus R squared Cox-Snell over S. S is the shrinkage target, 0.9.",
  },
  optimism: {
    tex: String.raw`S_4=\frac{R^{2}_{cs}}{R^{2}_{cs}+0.05\,\max(R^{2}_{cs})}`,
    aria: "S four equals R squared Cox-Snell divided by, R squared Cox-Snell plus 0.05 times the maximum R squared Cox-Snell.",
  },
  maxR2cs: {
    tex: String.raw`\max(R^{2}_{cs})=1-\left(\varphi^{\varphi}\,(1-\varphi)^{1-\varphi}\right)^{2}`,
    aria: "The maximum R squared Cox-Snell equals one minus, phi to the power phi times one minus phi to the power one minus phi, all squared.",
  },
  nagelkerke: {
    tex: String.raw`R^{2}_{Nagelkerke}=\frac{R^{2}_{cs}}{\max(R^{2}_{cs})}`,
    aria: "R squared Nagelkerke equals R squared Cox-Snell divided by the maximum R squared Cox-Snell.",
  },
  eppBinary: {
    tex: String.raw`\text{EPP}=\frac{n\,\varphi}{P}\qquad(\text{events}=n\,\varphi)`,
    aria: "Events per parameter equals n times phi over P, where the expected number of events is n times phi.",
  },
  eppSurvival: {
    tex: String.raw`\text{EPP}=\frac{n\cdot\text{rate}\cdot\overline{\text{fup}}}{P}`,
    aria: "Events per parameter equals n times the event rate times the mean follow-up, over P.",
  },
  residualSD: {
    tex: String.raw`n=234+P`,
    aria: "n equals 234 plus P. This is the continuous residual standard deviation precision criterion.",
  },
};

const here = dirname(fileURLToPath(import.meta.url));
const out = resolve(here, "../src/content/formulas.generated.ts");

const record = Object.fromEntries(
  Object.entries(FORMULAS).map(([key, { tex, aria }]) => [
    key,
    {
      aria,
      html: katex.renderToString(tex, {
        displayMode: true,
        output: "htmlAndMathml",
        throwOnError: true,
        strict: "warn",
      }),
    },
  ]),
);

const banner =
  "// AUTO-GENERATED by scripts/render-formulas.ts — do not edit by hand.\n" +
  "// Run: npm run gen:formulas\n\n";
writeFileSync(
  out,
  `${banner}export const FORMULAS = ${JSON.stringify(record, null, 2)} as const;\n\nexport type FormulaKey = keyof typeof FORMULAS;\n`,
);
console.log(`Wrote ${out} (${Object.keys(record).length} formulas)`);
